FROM python:3.12

# install poetry
RUN pip install -U pip poetry==1.7.1

WORKDIR /app

# install dependencies
COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-root

# copy files
COPY src /app/src
COPY tests /app/tests

# install the project as a package
RUN poetry install

COPY equal-shares-api-public-key.pem /app/
COPY equal-shares-api-private-key.pem /app/

ENTRYPOINT ["python", "-m", "pytest", "-k", "tests"]