FROM python:3.12

# install apt dependencies
RUN apt-get update && \
    apt-get install -y make

# install poetry
RUN pip install -U pip poetry==1.7.1

WORKDIR /app

# install dependencies
COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-root

# copy files
COPY . /app/

# install the project as a package
RUN poetry install

COPY equal-shares-api-public-key.pem /app/
COPY equal-shares-api-private-key.pem /app/

ENTRYPOINT ["make", "test"]
